# Generated by Django 3.2.3 on 2021-06-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_product_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tamano',
            field=models.CharField(default='XS', max_length=150),
        ),
    ]
