# Generated by Django 3.2.3 on 2021-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_product_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proveedor',
            field=models.CharField(default='sin proveedor', max_length=150),
        ),
    ]
