# Generated by Django 3.2.3 on 2021-07-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_product_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
