# Generated by Django 3.2.3 on 2021-07-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20210705_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
    ]
