# Generated by Django 3.2.3 on 2021-07-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_alter_product_tamano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proveedor',
            field=models.CharField(default='sin proveedor', max_length=150, null=True),
        ),
    ]
