# Generated by Django 3.2.3 on 2021-07-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/006.jpg', upload_to='product_images'),
        ),
    ]
